spring:
  config:
    import: optional:classpath:application-local.yml,optional:file:./application-local.yml,optional:file:./config/application-local.yml
  datasource:
    url: ${DB_URL:jdbc:mysql://db:3306/music_sync?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  redis:
    host: ${REDIS_HOST:redis} # Redis服务器地址
    database: ${REDIS_DATABASE:0} # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:6379} # Redis服务器连接端口
    password: ${REDIS_PASSWORD:} # Redis服务器连接密码（默认为空）
    timeout: ${REDIS_TIMEOUT:3000ms} # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.dxh.spotifysync: info
